### ISSUE TITLE
Please correct summary text

### ISSUE THREAD

**Issue by stweb75** [franciscomartinezdelrio/DGLMExtPois#1]
Nice package for mean parametrized CMP regression. I am using version  0.2.3
Please correct the summary for CMP, replacing the text:
  Dispersion model coefficients (with **logit** link):
with
  Dispersion model coefficients (with **log** link):
Example:
mod <- glm.CMP( ... mod.nu = y ~ 1 ...)
disp <- log (mod$nus[1]) # Dispersion model coefficients (with log link)
Thanks.

**Comment by franciscomartinezdelrio** [comment]
Done, thank you for your comments.
